name: CI

on:
  workflow_dispatch:

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Promotion
        uses: ./.github/actions/deployment_promotion
  
  stage:
    needs: dev
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Promotion
        uses: ./.github/actions/deployment_promotion

  preprod:
    needs: stage
    environment: preprod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Promotion
        uses: ./.github/actions/deployment_promotion

  prod:
    needs: preprod
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Promotion
        uses: ./.github/actions/deployment_promotion