name: CI

on:
  workflow_dispatch:

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, dev!
  
  stage:
    needs: dev
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, dev!

  preprod:
    needs: stage
    environment: preprod
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, dev!

  prod:
    needs: preprod
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, dev!
